apiVersion: v1
kind: Service
metadata:
  name: customerenquiry-api
spec:
  selector:
    app: customerenquiry-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
